#include <windows.h>
#include <stdio.h>
#include <string.h>

#define TIMER_SHOW_DISABLED 1
#define TIMER_ENABLE_TARGET 2
#define TIMER_MONITOR 3
#define TIMER_CLOSE 4
#define MODE_IMPOSTOR 1
#define MODE_SCOPED 2
#define MODE_NOOP_SELECTED 3
#define MODE_HIDDEN 4
#define MODE_DISABLED 5
#define MODE_MANUAL_RADIO 6
#define MODE_CHECKBOX 7
#define MODE_PUSH 8
#define MODE_OWNERDRAW 9
#define MODE_WRONG_RUNTIME_CLASS 10
#define MODE_AMBIGUOUS_PARENT 11
#define MODE_AMBIGUOUS_CONTROL 12
static const char *event_path=NULL; static int mode=0; static int target_control_id=0;
static HWND target_window=NULL,other_window=NULL,target_radio=NULL,sibling_radio=NULL,wrong_id_radio=NULL,other_window_radio=NULL,other_window_sibling=NULL;
static DWORD disabled_delay_ms=0; static int target_click_count=0,wrong_id_click_count=0,other_window_click_count=0,event_failure=0;
static DWORD parse_unsigned(const char *t){DWORD v=0;while(*t>='0'&&*t<='9'){v=v*10+(DWORD)(*t-'0');t++;}return v;}
static int append_event(const char *e){char line[384];int n=snprintf(line,sizeof(line),"%s\r\n",e);if(n<0||n>=(int)sizeof(line))return 1;HANDLE f=CreateFileA(event_path,FILE_APPEND_DATA,FILE_SHARE_READ|FILE_SHARE_WRITE,NULL,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);if(f==INVALID_HANDLE_VALUE)return 1;DWORD w=0;BOOL ok=WriteFile(f,line,(DWORD)n,&w,NULL);CloseHandle(f);return ok&&w==(DWORD)n?0:1;}
static void record_event(const char *e){if(append_event(e)!=0)event_failure=1;} static void record_violation(const char *e){record_event(e);}
static int checked_state(HWND c){LRESULT v=SendMessageA(c,BM_GETCHECK,0,0);if(v==BST_UNCHECKED)return 0;if(v==BST_CHECKED)return 1;return 2;}
static void set_checked(HWND c,int x){SendMessageA(c,BM_SETCHECK,x?BST_CHECKED:BST_UNCHECKED,0);}
static HWND create_top_level(HINSTANCE i,const char *cn,const char *title){return CreateWindowExA(0,cn,title,WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,680,420,NULL,NULL,i,NULL);}
static HWND create_control(HWND p,const char *cn,const char *txt,DWORD style,int id,int x,int y){return CreateWindowExA(0,cn,txt,WS_CHILD|style,x,y,230,34,p,(HMENU)(INT_PTR)id,GetModuleHandleA(NULL),NULL);}
static HWND create_button(HWND p,const char *txt,DWORD style,int id,int x,int y,int checked){HWND c=create_control(p,"Button",txt,style,id,x,y);if(c)set_checked(c,checked);return c;}
static int start_common_timers(DWORD life){return(SetTimer(target_window,TIMER_MONITOR,25,NULL)==0||SetTimer(target_window,TIMER_CLOSE,life,NULL)==0)?1:0;}
static void schedule_settle_close(HWND w){KillTimer(w,TIMER_CLOSE);if(SetTimer(w,TIMER_CLOSE,400,NULL)==0){event_failure=1;DestroyWindow(w);}}
static void monitor_state(void){if(target_radio&&IsWindow(target_radio)){int t=checked_state(target_radio);int s=sibling_radio&&IsWindow(sibling_radio)?checked_state(sibling_radio):-1;if(target_click_count>1)record_violation("VIOLATION-radio-target-clicked-more-than-once");if(mode==MODE_IMPOSTOR&&(target_click_count!=0||t!=0||s!=1))record_violation("VIOLATION-radio-other-process-mutated");if(mode==MODE_SCOPED){if(target_click_count==0&&(t!=0||s!=1))record_violation("VIOLATION-radio-target-or-sibling-changed-before-click");if(target_click_count==1&&(t!=1||s!=0))record_violation("VIOLATION-radio-click-did-not-select-target-and-clear-sibling");}if(mode==MODE_NOOP_SELECTED&&(target_click_count!=0||t!=1||s!=0))record_violation("VIOLATION-radio-noop-selected-mutated");if((mode==MODE_HIDDEN||mode==MODE_DISABLED||mode==MODE_MANUAL_RADIO||mode==MODE_CHECKBOX||mode==MODE_PUSH||mode==MODE_OWNERDRAW)&&(target_click_count!=0||t!=0))record_violation("VIOLATION-radio-rejected-control-mutated");}if(wrong_id_radio&&IsWindow(wrong_id_radio)&&(wrong_id_click_count!=0||checked_state(wrong_id_radio)!=0))record_violation("VIOLATION-radio-correct-class-wrong-id-mutated");if(other_window_radio&&IsWindow(other_window_radio)){int s=other_window_sibling&&IsWindow(other_window_sibling)?checked_state(other_window_sibling):-1;if(other_window_click_count!=0||checked_state(other_window_radio)!=0||s!=1)record_violation("VIOLATION-radio-other-window-mutated");}}
static void record_final_state(void){monitor_state();if(mode==MODE_IMPOSTOR&&checked_state(target_radio)==0&&checked_state(sibling_radio)==1&&target_click_count==0)record_event("radio-other-process-final-target-0-sibling-1-click-0");else if(mode==MODE_SCOPED){if(checked_state(target_radio)==1&&checked_state(sibling_radio)==0&&target_click_count==1)record_event("radio-target-final-target-1-sibling-0-click-1");if(checked_state(wrong_id_radio)==0&&wrong_id_click_count==0)record_event("radio-wrong-id-final-target-0-click-0");if(checked_state(other_window_radio)==0&&checked_state(other_window_sibling)==1&&other_window_click_count==0)record_event("radio-other-window-final-target-0-sibling-1-click-0");}else if(mode==MODE_NOOP_SELECTED&&checked_state(target_radio)==1&&checked_state(sibling_radio)==0&&target_click_count==0)record_event("radio-noop-final-target-1-sibling-0-click-0");}
static LRESULT CALLBACK window_proc(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_COMMAND:if(HIWORD(wp)==BN_CLICKED){HWND src=(HWND)lp;int id=LOWORD(wp);if(w==target_window&&src==target_radio&&id==target_control_id){target_click_count++;if(mode==MODE_SCOPED&&target_click_count==1){if(checked_state(target_radio)==1&&checked_state(sibling_radio)==0)record_event("radio-target-click-1-target-1-sibling-0");else record_violation("VIOLATION-radio-target-click-state-invalid");schedule_settle_close(w);}else record_violation("VIOLATION-radio-target-unexpected-click");return 0;}if(w==target_window&&src==wrong_id_radio&&id==target_control_id+1){wrong_id_click_count++;record_violation("VIOLATION-radio-wrong-id-clicked");return 0;}if(w==other_window&&src==other_window_radio&&id==target_control_id){other_window_click_count++;record_violation("VIOLATION-radio-other-window-clicked");return 0;}}break;case WM_TIMER:if(w!=target_window)return 0;if(wp==TIMER_SHOW_DISABLED&&mode==MODE_SCOPED){KillTimer(w,TIMER_SHOW_DISABLED);EnableWindow(target_radio,FALSE);ShowWindow(target_radio,SW_SHOW);UpdateWindow(target_radio);if(checked_state(target_radio)!=0||checked_state(sibling_radio)!=1||target_click_count!=0)record_violation("VIOLATION-radio-mutated-before-visible-disabled-stage");record_event("radio-target-visible-disabled-target-0-sibling-1-click-0");if(SetTimer(w,TIMER_ENABLE_TARGET,disabled_delay_ms,NULL)==0){event_failure=1;DestroyWindow(w);}return 0;}if(wp==TIMER_ENABLE_TARGET&&mode==MODE_SCOPED){KillTimer(w,TIMER_ENABLE_TARGET);if(checked_state(target_radio)!=0||checked_state(sibling_radio)!=1||target_click_count!=0)record_violation("VIOLATION-radio-mutated-before-enabled-stage");EnableWindow(target_radio,TRUE);record_event("radio-target-visible-enabled-target-0-sibling-1-click-0");return 0;}if(wp==TIMER_MONITOR){monitor_state();return 0;}if(wp==TIMER_CLOSE){KillTimer(w,TIMER_CLOSE);record_final_state();DestroyWindow(w);return 0;}break;case WM_CLOSE:DestroyWindow(w);return 0;case WM_DESTROY:if(w==target_window){if(other_window&&IsWindow(other_window))DestroyWindow(other_window);PostQuitMessage(0);}return 0;default:break;}return DefWindowProcA(w,m,wp,lp);}
static int create_radio_group(HWND p,int id,BOOL vis,BOOL en,int selected,HWND *os,HWND *ot,int x,int y){HWND s=create_button(p,"Option A",WS_VISIBLE|WS_GROUP|WS_TABSTOP|BS_AUTORADIOBUTTON,id+100,x,y,selected?0:1);HWND t=create_button(p,"Option B",(vis?WS_VISIBLE:0)|WS_TABSTOP|BS_AUTORADIOBUTTON,id,x,y+42,selected);HWND end=create_control(p,"Static","End group",WS_VISIBLE|WS_GROUP|SS_LEFT,id+101,x,y+84);if(!s||!t||!end)return 1;EnableWindow(t,en);*os=s;*ot=t;return 0;}
static int run_impostor(HINSTANCE i,const char *cn,const char *title,DWORD life){record_event("radio-impostor-start");target_window=create_top_level(i,cn,title);if(!target_window)return 4;if(create_radio_group(target_window,target_control_id,TRUE,TRUE,0,&sibling_radio,&target_radio,24,24))return 5;ShowWindow(target_window,SW_SHOW);UpdateWindow(target_window);record_event("radio-impostor-ready-target-0-sibling-1-click-0");return start_common_timers(life)?6:0;}
static int run_scoped(HINSTANCE i,const char *cn,const char *title,DWORD hidden,DWORD disabled,DWORD life){record_event("radio-scoped-start");target_window=create_top_level(i,cn,title);if(!target_window)return 4;HWND wc=create_control(target_window,"Static","Wrong class",WS_VISIBLE|WS_GROUP|SS_LEFT,target_control_id,360,24);wrong_id_radio=create_button(target_window,"Wrong ID",WS_VISIBLE|WS_GROUP|BS_AUTORADIOBUTTON,target_control_id+1,360,68,0);HWND manual=create_button(target_window,"Manual radio",WS_VISIBLE|WS_GROUP|BS_RADIOBUTTON,target_control_id+2,360,112,0);HWND cb=create_button(target_window,"Checkbox",WS_VISIBLE|WS_GROUP|BS_AUTOCHECKBOX,target_control_id+3,360,156,0);HWND push=create_button(target_window,"Push",WS_VISIBLE|WS_GROUP|BS_PUSHBUTTON,target_control_id+4,360,200,0);HWND owner=create_button(target_window,"Ownerdraw",WS_VISIBLE|WS_GROUP|BS_OWNERDRAW,target_control_id+5,360,244,0);if(!wc||!wrong_id_radio||!manual||!cb||!push||!owner)return 5;if(create_radio_group(target_window,target_control_id,FALSE,TRUE,0,&sibling_radio,&target_radio,24,24))return 6;ShowWindow(target_window,SW_SHOW);UpdateWindow(target_window);record_event("radio-selector-decoys-ready");record_event("radio-target-hidden-target-0-sibling-1-click-0");other_window=create_top_level(i,cn,"Different Radio Trainer Window");if(!other_window)return 7;if(create_radio_group(other_window,target_control_id,TRUE,TRUE,0,&other_window_sibling,&other_window_radio,24,24))return 8;ShowWindow(other_window,SW_SHOW);UpdateWindow(other_window);record_event("radio-other-window-ready-target-0-sibling-1-click-0");disabled_delay_ms=disabled;if(SetTimer(target_window,TIMER_SHOW_DISABLED,hidden,NULL)==0||start_common_timers(life))return 9;return 0;}
static int run_single(HINSTANCE i,const char *cn,const char *title,DWORD style,BOOL vis,BOOL en,int selected,const char *ready,DWORD life){target_window=create_top_level(i,cn,title);if(!target_window)return 4;if(style==BS_AUTORADIOBUTTON){if(create_radio_group(target_window,target_control_id,vis,en,selected,&sibling_radio,&target_radio,24,24))return 5;}else{target_radio=create_button(target_window,"Target",(vis?WS_VISIBLE:0)|WS_GROUP|style,target_control_id,24,24,0);if(!target_radio)return 5;EnableWindow(target_radio,en);}ShowWindow(target_window,SW_SHOW);UpdateWindow(target_window);record_event(ready);return start_common_timers(life)?6:0;}
static int run_wrong_runtime_class(HINSTANCE i,const char *cn,const char *title,DWORD life){target_window=create_top_level(i,cn,title);if(!target_window)return 4;HWND c=create_control(target_window,"Static","Wrong runtime class",WS_VISIBLE|SS_LEFT,target_control_id,24,24);if(!c)return 5;ShowWindow(target_window,SW_SHOW);UpdateWindow(target_window);record_event("radio-wrong-runtime-class-ready");return start_common_timers(life)?6:0;}
static int run_ambiguous_parent(HINSTANCE i,const char *cn,const char *title,DWORD life){target_window=create_top_level(i,cn,title);other_window=create_top_level(i,cn,title);if(!target_window||!other_window)return 4;if(create_radio_group(target_window,target_control_id,TRUE,TRUE,0,&sibling_radio,&target_radio,24,24))return 5;HWND ds=NULL;if(create_radio_group(other_window,target_control_id,TRUE,TRUE,0,&ds,&other_window_radio,24,24))return 6;other_window_sibling=ds;ShowWindow(target_window,SW_SHOW);ShowWindow(other_window,SW_SHOW);UpdateWindow(target_window);UpdateWindow(other_window);record_event("radio-ambiguous-parent-ready");return start_common_timers(life)?7:0;}
static int run_ambiguous_control(HINSTANCE i,const char *cn,const char *title,DWORD life){target_window=create_top_level(i,cn,title);if(!target_window)return 4;target_radio=create_button(target_window,"Target one",WS_VISIBLE|WS_GROUP|BS_AUTORADIOBUTTON,target_control_id,24,24,0);wrong_id_radio=create_button(target_window,"Target two",WS_VISIBLE|WS_GROUP|BS_AUTORADIOBUTTON,target_control_id,24,68,0);if(!target_radio||!wrong_id_radio)return 5;ShowWindow(target_window,SW_SHOW);UpdateWindow(target_window);record_event("radio-ambiguous-control-ready");return start_common_timers(life)?6:0;}
int main(int argc,char **argv){if(argc!=8)return 2;event_path=argv[1];const char *mn=argv[2],*title=argv[3];target_control_id=(int)parse_unsigned(argv[4]);DWORD d1=parse_unsigned(argv[5]),d2=parse_unsigned(argv[6]),life=parse_unsigned(argv[7]);if(strcmp(mn,"impostor")==0)mode=MODE_IMPOSTOR;else if(strcmp(mn,"scoped")==0)mode=MODE_SCOPED;else if(strcmp(mn,"noop-selected")==0)mode=MODE_NOOP_SELECTED;else if(strcmp(mn,"hidden")==0)mode=MODE_HIDDEN;else if(strcmp(mn,"disabled")==0)mode=MODE_DISABLED;else if(strcmp(mn,"manual-radio")==0)mode=MODE_MANUAL_RADIO;else if(strcmp(mn,"checkbox")==0)mode=MODE_CHECKBOX;else if(strcmp(mn,"push")==0)mode=MODE_PUSH;else if(strcmp(mn,"ownerdraw")==0)mode=MODE_OWNERDRAW;else if(strcmp(mn,"wrong-runtime-class")==0)mode=MODE_WRONG_RUNTIME_CLASS;else if(strcmp(mn,"ambiguous-parent")==0)mode=MODE_AMBIGUOUS_PARENT;else if(strcmp(mn,"ambiguous-control")==0)mode=MODE_AMBIGUOUS_CONTROL;else return 2;HINSTANCE i=GetModuleHandleA(NULL);WNDCLASSA wc={0};wc.lpfnWndProc=window_proc;wc.hInstance=i;wc.lpszClassName="TandemRadioSmokeHelper";if(!RegisterClassA(&wc)&&GetLastError()!=ERROR_CLASS_ALREADY_EXISTS)return 3;int r=0;if(mode==MODE_IMPOSTOR)r=run_impostor(i,wc.lpszClassName,title,life);else if(mode==MODE_SCOPED)r=run_scoped(i,wc.lpszClassName,title,d1,d2,life);else if(mode==MODE_NOOP_SELECTED)r=run_single(i,wc.lpszClassName,title,BS_AUTORADIOBUTTON,TRUE,TRUE,1,"radio-noop-ready-target-1-sibling-0-click-0",life);else if(mode==MODE_HIDDEN)r=run_single(i,wc.lpszClassName,title,BS_AUTORADIOBUTTON,FALSE,TRUE,0,"radio-hidden-ready-target-0-sibling-1-click-0",life);else if(mode==MODE_DISABLED)r=run_single(i,wc.lpszClassName,title,BS_AUTORADIOBUTTON,TRUE,FALSE,0,"radio-disabled-ready-target-0-sibling-1-click-0",life);else if(mode==MODE_MANUAL_RADIO)r=run_single(i,wc.lpszClassName,title,BS_RADIOBUTTON,TRUE,TRUE,0,"radio-manual-ready-target-0-click-0",life);else if(mode==MODE_CHECKBOX)r=run_single(i,wc.lpszClassName,title,BS_AUTOCHECKBOX,TRUE,TRUE,0,"radio-checkbox-ready-target-0-click-0",life);else if(mode==MODE_PUSH)r=run_single(i,wc.lpszClassName,title,BS_PUSHBUTTON,TRUE,TRUE,0,"radio-push-ready-target-0-click-0",life);else if(mode==MODE_OWNERDRAW)r=run_single(i,wc.lpszClassName,title,BS_OWNERDRAW,TRUE,TRUE,0,"radio-ownerdraw-ready-target-0-click-0",life);else if(mode==MODE_WRONG_RUNTIME_CLASS)r=run_wrong_runtime_class(i,wc.lpszClassName,title,life);else if(mode==MODE_AMBIGUOUS_PARENT)r=run_ambiguous_parent(i,wc.lpszClassName,title,life);else if(mode==MODE_AMBIGUOUS_CONTROL)r=run_ambiguous_control(i,wc.lpszClassName,title,life);if(r)return r;MSG msg;while(GetMessageA(&msg,NULL,0,0)>0){TranslateMessage(&msg);DispatchMessageA(&msg);}return event_failure?20:0;}
